# Generated by Django 3.2.4 on 2021-07-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('quantity', models.CharField(max_length=100)),
                ('avgprice', models.IntegerField()),
            ],
        ),
    ]
