# Generated by Django 3.2.4 on 2021-07-05 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('ticker', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('avg_buy_price', models.FloatField()),
                ('share', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='transact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ticker', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=200)),
            ],
        ),
    ]
