# Generated by Django 3.2.4 on 2021-07-01 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_alter_share_avgprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='avgprice',
            new_name='avgBuyPrice',
        ),
    ]
