# Generated by Django 3.2.4 on 2021-07-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_rename_avgprice_share_avgbuyprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('ticker', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('avg_buy_price', models.FloatField()),
                ('share', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='transact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='share',
        ),
    ]
