# Generated by Django 3.2.4 on 2021-07-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20210702_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transact',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transact',
            name='ticker',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transact',
            name='type',
            field=models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=200),
        ),
    ]
