# Generated by Django 3.2.4 on 2021-07-04 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_auto_20210703_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transact',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
