# Generated by Django 3.2.4 on 2021-07-05 10:11

from django.db import migrations, models
import trade.models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_alter_transact_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='share',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='ticker',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
